# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 33b8dba9202531c7287c691cda46ccf83fb494a08f588f1af76bea62815532ea67032e5e34d655f3d50804b8b6da445ba96d7c1ba574b6e034d64ec62494e442

test:
  secret_key_base: 33b8dba9202531c7287c691cda46ccf83fb494a08f588f1af76bea62815532ea67032e5e34d655f3d50804b8b6da445ba96d7c1ba574b6e034d64ec62494e442

staging:
  secret_key_base: 83fda52cd1dc18e9b0253cc8a2338da2cd99e2e7a049009c28a6496c1377624aabde97ceb28ff7156ae705559efb252fcc97aa6addf3a9b19f976a8b66f5b70e

staging:
  secret_key_base: 83fda52cd1dc18e9b0253cc8a2338da2cd99e2e7a049009c28a6496c1377624aabde97ceb28ff7156ae705559efb252fcc97aa6addf3a9b19f976a8b66f5b70e
# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
